version: "3.8"
services:
  backend:
    build: ./server
    command: yarn dev
    restart: on-failure
    image: backend
    volumes:
      - ./server/dist/:/usr/src/app/dist/
      - ./server/src/:/usr/src/app/src/
      - ./server/public/images/:/usr/src/app/public/images
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      FRONTEND_CORS_ORIGIN: ${FRONTEND_CORS_ORIGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./web
    command: yarn dev
    restart: on-failure
    image: frontend
    volumes:
      - ./web/:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
